#include "testing.h"

int main(int argc, const char **argv)
{
    tests_arg_parse(&argc, &argv);

    TEST_BEGIN("Case1");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case2");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case3");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case4");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case5");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case6");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case7");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case8");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case9");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case10");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case11");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case12");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case13");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case14");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case15");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case16");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case17");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case18");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case19");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case20");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case21");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case22");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case23");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case24");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case25");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case26");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case27");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case28");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case29");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case30");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case31");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case32");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case33");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case34");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case35");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case36");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case37");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case38");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case39");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case40");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case41");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case42");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case43");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case44");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case45");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case46");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case47");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case48");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case49");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case50");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case51");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case52");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case53");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case54");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case55");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case56");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case57");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case58");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case59");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case60");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case61");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case62");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case63");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case64");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case65");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case66");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case67");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case68");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case69");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case70");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case71");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case72");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case73");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case74");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case75");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case76");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case77");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case78");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case79");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case80");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case81");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case82");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case83");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case84");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case85");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case86");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case87");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case88");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case89");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case90");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case91");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case92");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case93");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case94");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case95");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case96");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case97");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case98");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case99");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    TEST_BEGIN("Case100");
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);
    TEST_EQI(1, 1);

    return tests_end();
}
