/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

/*=======Structure Used By Test Runner=====*/
struct UnityRunTestParameters
{
  UnityTestFunction func;
  const char* name;
  UNITY_LINE_TYPE line_num;
};

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_t1(void);
extern void test_t2(void);
extern void test_t3(void);
extern void test_t4(void);
extern void test_t5(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Setup (stub)=====*/
void setUp(void) {}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("autogen-sample/t5.c");

  int number_of_tests = 5;
  struct UnityRunTestParameters run_test_params_arr[number_of_tests];

  run_test_params_arr[0].func = test_t1;
  run_test_params_arr[0].name = "test_t1";
  run_test_params_arr[0].line_num = 3;
  run_test_params_arr[1].func = test_t2;
  run_test_params_arr[1].name = "test_t2";
  run_test_params_arr[1].line_num = 7;
  run_test_params_arr[2].func = test_t3;
  run_test_params_arr[2].name = "test_t3";
  run_test_params_arr[2].line_num = 11;
  run_test_params_arr[3].func = test_t4;
  run_test_params_arr[3].name = "test_t4";
  run_test_params_arr[3].line_num = 15;
  run_test_params_arr[4].func = test_t5;
  run_test_params_arr[4].name = "test_t5";
  run_test_params_arr[4].line_num = 19;

  for (int i = 0; i < number_of_tests; i++)
  {
    run_test(run_test_params_arr[i].func, run_test_params_arr[i].name, run_test_params_arr[i].line_num);
  }

  return UNITY_END();
}
